### ISSUE TITLE
Running error in Idea

### ISSUE THREAD

**Issue by zikolach** [pocorall/hello-scaloid-sbt#14]
First time project runs perfect. After removing something (e.g. call of fill method on SEditText), re-running app, reverting changes and running again I'm getting following error:
```
01-21 13:14:39.952    1447-1447/scaloid.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: org.scaloid.common.SEditText.fill
            at scaloid.example.HelloScaloid$$anonfun$2$$anon$1.<init>(HelloScaloid.scala:22)
            at scaloid.example.HelloScaloid$$anonfun$2.apply(HelloScaloid.scala:9)
            at scaloid.example.HelloScaloid$$anonfun$2.apply(HelloScaloid.scala:9)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:130)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:130)
            at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
            at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
            at org.scaloid.common.SActivity$class.onCreate(app.scala:130)
            at scaloid.example.HelloScaloid.onCreate(HelloScaloid.scala:6)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```
To workaround this I added one more "before launch" line to run configuration with sbt clean task. "sbt ~run" from the console works correctly.

**Comment by tuvistavie** [comment]
I am having the same issue. Impossible to use `~run` as when I use a method that was not used during the build where proguard ran, I get a `NoSuchMethodError`.

**Comment by pocorall** [comment]
That's because the proguard cache doesn't have `fill` method when it is re-appeared. Clean rebuild could solve this, but it takes too long, as you know. Instead, run sbt command `android:package`. It will reconstruct proguard cache without recompiling entire project.
