### ISSUE TITLE
Run app error

### ISSUE THREAD

**Issue by Claus1** [pocorall/hello-scaloid-sbt#19]
c:\MyProjects\hello-scaloid-sbt-master>sbt run
[info] Loading project definition from C:\MyProjects\hello-scaloid-sbt-master\pr
oject
[info] Set current project to hello-scaloid-sbt (in build file:/C:/MyProjects/he
llo-scaloid-sbt-master/)
[info] Processing resources
[info] Compiling 2 Scala sources and 2 Java sources to C:\MyProjects\hello-scalo
id-sbt-master\bin\classes...
[warn] UPDATE: A newer android-sdk-plugin is available: 1.4.0, currently running
: 1.3.23
java.lang.IllegalArgumentException: invalid source release: 1.7
        at com.sun.tools.javac.main.RecognizedOptions$GrumpyHelper.error(Recogni
zedOptions.java:75)
        at com.sun.tools.javac.main.RecognizedOptions$13.process(RecognizedOptio
ns.java:370)
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:247)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:207)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:53)
        at sbt.compiler.javac.LocalJavaCompiler.run(LocalJava.scala:69)
        at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompil
erAdapter.scala:31)
        at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV
$sp(AnalyzingJavaCompiler.scala:65)
        at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(Ana
lyzingJavaCompiler.scala:65)
        at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(Ana
lyzingJavaCompiler.scala:65)
        at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.
scala:93)
        at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompile
r.scala:64)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mc
V$sp(MixedAnalyzingCompiler.scala:61)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(Mi
xedAnalyzingCompiler.scala:61)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(Mi
xedAnalyzingCompiler.scala:61)
        at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scal
a:75)
        at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompi
ler.scala:60)
        at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.sc
ala:65)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.
scala:160)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.
scala:160)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:6
6)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:6
4)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
        at sbt.inc.Incremental$.compile(Incremental.scala:61)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
        at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:128)
        at sbt.Compiler$.compile(Compiler.scala:114)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala
:814)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
05)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
03)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
6)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:662)
[error] (compile:compileIncremental) java.lang.IllegalArgumentException: invalid
 source release: 1.7
[error] Total time: 9 s, completed 09.06.2015 22:37:30

**Comment by pocorall** [comment]
Check that you are running JDK 1.7 or above.
