### ISSUE TITLE
Can not add new activity class to Scaloid project

### ISSUE THREAD

**Issue by CodeCombiner** [pocorall/hello-scaloid-sbt#23]
Hi guys

I have imported project by readme to Idea 15. It runs normally. When I copy HelloScaloid activity class to HelloScaloid2 - it can not be started from HelloScaloid activity. The acitivity also has been added to manifest and proguard-sbt

` startActivity(SIntent[HelloScaloid2])`

`05-02 20:43:48.446    3136-3136/scaloid.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: scaloid.example, PID: 3136
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/scaloid/common/SIntent$;
            at scaloid.example.HelloScaloid$$anonfun$1.apply$mcV$sp(HelloScaloid.scala:27)
            at scaloid.example.HelloScaloid$$anonfun$1.apply(HelloScaloid.scala:10)
            at scaloid.example.HelloScaloid$$anonfun$1.apply(HelloScaloid.scala:10)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1$$anonfun$apply$mcV$sp$1.apply(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1$$anonfun$apply$mcV$sp$1.apply(app.scala:144)
            at scala.collection.Iterator$class.foreach(Iterator.scala:742)
            at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
            at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
            at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply$mcV$sp(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:144)
            at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
            at org.scaloid.common.SActivity$class.onCreate(app.scala:143)
            at scaloid.example.HelloScaloid.onCreate(HelloScaloid.scala:6)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.scaloid.common.SIntent$" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/scaloid.example-1/base.apk"],nativeLibraryDirectories=[/data/app/scaloid.example-1/lib/x86_64, /vendor/lib64, /system/lib64]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at scaloid.example.HelloScaloid$$anonfun$1.apply$mcV$sp(HelloScaloid.scala:27)
            at scaloid.example.HelloScaloid$$anonfun$1.apply(HelloScaloid.scala:10)
            at scaloid.example.HelloScaloid$$anonfun$1.apply(HelloScaloid.scala:10)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1$$anonfun$apply$mcV$sp$1.apply(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1$$anonfun$apply$mcV$sp$1.apply(app.scala:144)
            at scala.collection.Iterator$class.foreach(Iterator.scala:742)
            at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
            at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
            at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply$mcV$sp(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:144)
            at org.scaloid.common.SActivity$$anonfun$onCreate$1.apply(app.scala:144)
            at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
            at org.scaloid.common.SActivity$class.onCreate(app.scala:143)
            at scaloid.example.HelloScaloid.onCreate(HelloScaloid.scala:6)
            at android.app.Activity.performCreate(Activity.java:6237)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Suppressed: java.lang.ClassNotFoundException: org.scaloid.common.SIntent$
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 28 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

The app runs via Play button in idea

**Comment by CodeCombiner** [comment]
It seems that the problem is somewhere in tools (Idea, sbt plugin or Android plugin), not in Scaloid project.
